config/routes.rb
Rails.application.routes.draw do
  resources :assignments
  resources :tickets
  resources :departaments
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
 
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/signup',  to: 'users#create'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  has_one :ticket
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]

  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
  end

  # GET /assignments/1/edit
  def edit
  end

  # POST /assignments
  # POST /assignments.json
  def create
    p 'hola assignments'
     p params
    @assignment = Assignment.new(assignment_params)

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1
  # PATCH/PUT /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to assignments_path, notice: 'Assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to assignments_url, notice: 'Assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assignment_params
      params.require(:assignment).permit(:status, :description)
    end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<li>
<%= form_for(assignment) do |f| %>
  <% if assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% assignment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</li>

app/views/assignments/edit.html.erb
<% provide(:title, 'Editing Assignment') %>
<% provide(:button_text, 'Editing Assignment') %>
<h1>Editing Assignment</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form', assignment: @assignment %>
    <%= link_to 'Back', assignments_path, class: "btn btn-info" %>
  </div>
</div>

app/views/assignments/index.html.erb
<% unless current_user.admin? %>
  <p id="notice"><%= notice %></p>

  <h1>Assignments</h1>

  <div class="row">
    <div class="col-xs-6 col-sm-6 col-md-12">
      <div class="text-center">
        <%= link_to 'New Ticket', new_ticket_path, class: "btn btn-primary " %>
        
      </div>
    </div>
  </div>
  <br>


  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <table style="HEIGHT:100%;WIDTH:100%;" >
      <tr>
        <th>Numero</th>
        <th>Asunto</th>
        <th>Description</th>
        <th>Estado</th>
        
      </tr>
    
      <% user1 = User.find(current_user)%>
      <% user1.assignments.each do |assignment| %>
          <% ticket = Ticket.find(assignment.ticket_id) %>
              <tr>
                 <td>Ticket <%= ticket.id%></td>
                 <td><%= ticket.name%></td>
                 <td><%= ticket.description%></td>
                 <td><%= assignment.status%></td>   
              </tr>    
         <% end %>

    </table>
  </div>
<% end %>



<% if current_user.admin? %>
  <p id="notice"><%= notice %></p>

  <h1>Assignments</h1>

  <div class="row">
    <div class="col-xs-6 col-sm-6 col-md-12">
      <div class="text-center">
        <%= link_to 'New Ticket', new_ticket_path, class: "btn btn-primary " %>
        
      </div>
    </div>
  </div>
  <br>


  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <table>
      <tr>
        <th>Numero</th>
        <th>Persona</th>
        <th>Asunto</th>
        <th>Description</th>
        <th>Estado</th>
        <th>Editar</th>
        <th>Eliminar</th>
      </tr>
    
      <% assignment1 = Assignment.all %>
          <% assignment1.each do |assignment| %>
          <% ticket = Ticket.find(assignment.ticket_id) %>
              <tr>
                 <td>Ticket <%= ticket.id%></td>
                 <td><%= assignment.user.name %></td>
                 <td>Ticket <%= ticket.name%></td>

                 
                 <td><%= assignment.description%></td> 
                 <td><%= assignment.status%></td> 
                
                
                 <td><%= link_to 'Edit', edit_assignment_path(assignment), class: "btn btn-warning btn-table"  %></td>
                 <td><%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-table" %></td>
                </tr>    
         <% end %>
    </table>
  </div>
<% end %>

app/views/assignments/new.html.erb
<h1>New Assignment</h1>

<%= render 'form', assignment: @assignment %>

<%= link_to 'Back', assignments_path %>

app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @assignment.status %>
</p>

<p>
  <strong>Description:</strong>
  <%= @assignment.description %>
</p>

<%= link_to 'Edit', edit_assignment_path(@assignment) %> |
<%= link_to 'Back', assignments_path %>