config/routes.rb
Rails.application.routes.draw do
  resources :assignments
  resources :tickets
  resources :departaments
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
 
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/signup',  to: 'users#create'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
end

app/models/departament.rb
class Departament < ApplicationRecord
  has_many :tickets, dependent: :delete_all
  validates :name, presence: true
  has_many :users, dependent: :delete_all
end

app/controllers/departaments_controller.rb
class DepartamentsController < ApplicationController
  before_action :set_departament, only: [:show, :edit, :update, :destroy]

  # GET /departaments
  # GET /departaments.json
  def index
    @departaments = Departament.all
  end

  # GET /departaments/1
  # GET /departaments/1.json
  def show
  end

  # GET /departaments/new
  def new
    @departament = Departament.new
  end

  # GET /departaments/1/edit
  def edit
  end

  # POST /departaments
  # POST /departaments.json
  def create
    @departament = Departament.new(departament_params)

    respond_to do |format|
      if @departament.save
        format.html { redirect_to departaments_path, notice: 'Departament was successfully created.' }
        format.json { render :show, status: :created, location: @departament }
      else
        format.html { render :new }
        format.json { render json: @departament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departaments/1
  # PATCH/PUT /departaments/1.json
  def update
    respond_to do |format|
      if @departament.update(departament_params)
        format.html { redirect_to departaments_path, notice: 'Departament was successfully updated.' }
        format.json { render :show, status: :ok, location: @departament }
      else
        format.html { render :edit }
        format.json { render json: @departament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departaments/1
  # DELETE /departaments/1.json
  def destroy
    @departament.destroy
    respond_to do |format|
      format.html { redirect_to departaments_url, notice: 'Departament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departament
      @departament = Departament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def departament_params
      params.require(:departament).permit(:name, :description)
    end
end

app/helpers/departaments_helper.rb
module DepartamentsHelper
end

app/views/departaments/_form.html.erb
<%= form_for(departament) do |f| %>
  <% if departament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(departament.errors.count, "error") %> prohibited this departament from being saved:</h2>

      <ul>
      <% departament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control'%>
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/departaments/edit.html.erb
<% provide(:title, 'Editing Departament') %>
<% provide(:button_text, 'Editing Departament') %>
<h1>Editing Departament</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
<%= render 'form', departament: @departament %><br>


<%= link_to 'Back', departaments_path, class: "btn btn-info" %>

app/views/departaments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departaments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departaments.each do |departament| %>
      <tr>
        <td><%= departament.name %></td>
        <td><%= departament.description %></td>
        <td><%= link_to 'Show', departament %></td>
        <td><%= link_to 'Edit', edit_departament_path(departament) %></td>
        <td><%= link_to 'Destroy', departament, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Departament', new_departament_path %>

app/views/departaments/new.html.erb
<% provide(:title, 'Create Departament') %>
<% provide(:button_text, 'Create Departament') %>
<h1>Create Departament</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form', departament: @departament %>
  </div>
</div>

app/views/departaments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @departament.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @departament.description %>
</p>

<%= link_to 'Edit', edit_departament_path(@departament) %> |
<%= link_to 'Back', departaments_path %>