config/routes.rb
Rails.application.routes.draw do
  resources :assignments
  resources :tickets
  resources :departaments
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
 
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/signup',  to: 'users#create'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :departament
  has_one :assignment
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 10 }
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create

    user = User.find(current_user.id)
    p 'hola user' *10
    p user.departament_id
    p ticket_params[:name]
     p 'hola user' *10
    @ticket = Ticket.create(name: ticket_params[:name],  description: ticket_params[:description], departament_id: user.departament_id)
    p 'buchon' *100
    p session[:user_id] 
        p 'buchon' *100
    p params 
    p @ticket

    #crear la asignación
    @assignment = Assignment.create(status: "iniciado", description: @ticket.description, user_id: current_user.id, ticket_id: @ticket.id)

    #mostrar mensaje de creada la asignación
    p "*" * 50
    p @assignment.ticket_id
    # respond_to do |format|
    #   if @assignment
    #     format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
    #     format.json { render :show, status: :created, location: @ticket }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @ticket.errors, status: :unprocessable_entity }
    #   end
    # end

    respond_to do |format|
        if @assignment.save
          format.html { redirect_to assignments_path, notice: 'Assignment was successfully created.' }
          format.json { render :index, status: :created, location: @assignment }
         #assignments_path 
        else
          format.html { render :new }
          format.json { render json: @assignment.errors, status: :unprocessable_entity }
        end
      end
    end    


  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:name, :description, :departament_id)
    end

    def assignment_params
      params.require(:assignment).permit(:status, :description, :user_id, :ticket_id)
    end
    
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
 
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<% unless current_user.admin? %>
<p id="notice"><%= notice %></p>
<h1>Tickets</h1>

<div class="row">
  <div class="col-sm-12">
    <div class="text-center">
      <%= link_to 'New Ticket', new_ticket_path, class: "btn btn-primary " %>
      
    </div>
  </div>
</div>
<br>

<table>
  <thead>
    <tr>
      <th>Numero</th>
      <th>Description</th>
      <th>Satatus</th>
      <th>Departament</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% user1 = User.find(current_user)%>
      <% user1.departament.tickets.each do |departamento| %>
      <% user1.assignments.each do |assignment| %>      
        <tr>  
          <td>Ticket <%= departamento.id%></td>
          <td><%= departamento.description%></td>
          <td><%= assignment.status%></td>
          <td><%= departamento.name%></td>
        
          <td><%= link_to 'Show', departamento %></td>
          <td><% %>
          </td>     
        </tr>
          <% end %>
    <% end %>
  </tbody>
</table>
<br>

<% end %>


<% if current_user.admin? %>
<p id="notice"><%= notice %></p>
<h1>Tickets</h1>
<div class="row">
  <div class="col-sm-12">
    <div class="text-center">
      <%= link_to 'New Ticket', new_ticket_path, class: "btn btn-primary " %>
      <%= link_to 'Tickets Asignados', assignments_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>
<br>
<table>
  <thead>
    <tr>
      <th>Numero</th>
      <th>Name</th>
      <th>Description</th>
      <th>Mostrar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td>Ticket <%= ticket.id %></td>
        <td><%= ticket.name %></td>
        <td><%= ticket.description %></td>
        <td><%= link_to 'Show', ticket %></td>
        
          <td><%= link_to 'Edit', edit_ticket_path(ticket), class: "btn btn-success"  %> </td>
         <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary"  %></td>
     
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/tickets/new.html.erb
<% provide(:title, 'Create help desk') %>
<% provide(:button_text, 'Create my ticket') %>
<h1>Create help desk</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Namevr:</strong>
  <%= @ticket.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ticket.description %>
</p>



<%= link_to 'Edit', edit_ticket_path(@ticket), class: "btn btn-success"  %> |
<%= link_to 'Back', tickets_path, class: "btn btn-primary"  %>